Include send btc transaction function
secretkeylabs/sats-connect pull request #8
Opened 2023-05-19 12:43 UTC by Imamah-Zafar

2023-05-25 09:24 UTC, abdulhaseeb4239 requested changes

2023-05-25 19:02 UTC, yknl commented on src/transactions/sendBtcTransaction.ts
> +  satsAmount: string;
amountSats makes more sense here

2023-05-26 08:38 UTC, Imamah-Zafar commented on src/transactions/sendBtcTransaction.ts
> +  message: string;
all of the previous implemented functions do have `message` attribute in its payload. For reference check GetAddressPayload, SignTransactionPayload, SignMessagePayload

for the sake of being consistent, shouldnt the message attribute also be for `SendBtcTransactionPayload`

2023-05-26 09:03 UTC, abdulhaseeb4239 commented on src/transactions/sendBtcTransaction.ts
> +  message: string;
I am not sure why we need a message for a BTC transaction request, we should make it optional if anything

2023-06-05 07:43 UTC, abdulhaseeb4239 approved these changes

2023-06-06 11:10 UTC, DuskaT021 commented
This is tested together with Imamah and it can be merged

2023-06-06 11:10 UTC, merged